
vocabWords =  {"""ALLEGORY""":"""story or poem in which characters, settings, and events stand for other people or events or for abstract ideas or qualities. Example: Animal Farm, Dante\'s Inferno, and Lord of the Flies""",
"""ALLUSION""":"""reference to someone or something that is known from history, literature, religion, politics, sports, science, or another branch of culture. An indirect reference to something (usually from literature, etc.)""",
"""AMBIGUITY""":"""deliberately suggesting two or more different, and sometimes conflicting, meanings in a work. An event or situation that may be interpreted in more than one way-- this is done on purpose by the author, when it is not done on purpose, it is vagueness, and detracts from the work.""",
"""ANALOGY""":"""Comparison made between two things to show how they are alike""",
"""ANECDOTE""":"""Brief story, told to illustrate a point or serve as an example of something, often shows character of an individual""",
"""ANTAGONIST""":"""Opponent who struggles against or blocks the hero, or protagonist, in a story.""",
"""ANTIHERO""":"""Central character who lacks all the qualities traditionally associated with heroes. may lack courage, grace, intelligence, or moral scruples.""",
"""ANTHROPOMORPHISM""":"""a figure of speech in which human specific characteristics are attributed to animals other than humans (Example: Mickey Mouse dancing)""",
"""APHORISM""":"""brief, cleverly worded statement that makes a wise observation about life, or of a principle or accepted general truth. Also called maxim, epigram.""",
"""APOSTROPHE""":"""calling out to an imaginary, dead, or absent person, or to a place or thing, or a personified abstract idea. If the character is asking a god or goddess for inspiration it is called an invocation. """,
"""ARCHETYPE""":"""A recurring symbol, character, landscape, or event found throughout myth and literature across different cultures and eras. In terms of structure, it merely serves as a model from which writers create different versions and copies.""",
"""ASSONANCE""":"""the repetition of similar vowel sounds followed by different consonant sounds especially in words that are together.""",
"""ASYNDETON""":"""Commas used without conjunction to separate a series of words, thus emphasizing the parts equally: instead of X, Y, and Z... the writer uses X,Y,Z.... see polysyndeton.""",
"""ATMOSPHERE""":"""The dominant feeling that is created by a particular setting.""",
"""BILDUNGSROMAN""":"""A German term for \"novel of growth and development\". They generally depict a youth who struggles toward maturity, forming a worldview or philosophy of life and leaving behind the concerns of adolescence. Ex. Great Expectations.""",
"""CACOPHONY""":"""A harsh, discordant mixture of sounds. Ex. \"Grate on the scrannel pipes of wretched straw\" (John Milton)""",
"""CHARACTERIZATION""":"""the process by which the writer reveals the personality of a character.""",
"""INDIRECT CHARACTERIZATION""":"""the author reveals to the reader what the character is like by describing how the character looks and dresses, by letting the reader hear what the character says, by revealing the character\'s private thoughts and feelings, by revealing the characters effect on other people (showing how other characters feel or behave toward the character), or by showing the character in action. Common in modern literature.""",
"""DIRECT CHARACTERIZATION""":"""the author tells us directly what the character is like: sneaky, generous, mean to pets and so on. Romantic style literature relied more heavily on this form.""",
"""STATIC CHARACTER""":"""is one who does not change much in the course of a story.""",
"""DYNAMIC CHARACTER""":"""is one who changes in some important way as a result of the story\'s action.""",
"""FLAT CHARACTER""":"""has only one or two personality traits. They are one dimensional, like a piece of cardboard. They can be summed up in one phrase.""",
"""ROUND CHARACTER""":"""has more dimensions to their personalities---they are complex, just as real people are.""",
"""CLICHÉ""":"""is a word or phrase, often a figure of speech, that has become lifeless because of overuse. Avoid clichés like the plague. (That one is intended.)""",
"""CONFLICT""":"""the struggle between opposing forces or characters in a story.""",
"""EXTERNAL CONFLICT""":"""conflicts can exist between two people, between a person and nature or a machine or between a person a whole society.""",
"""INTERNAL CONFLICT""":"""a conflict can be internal, involving opposing forces within a person\'s mind..""",
"""CONNOTATION""":"""the associations and emotional overtones that have become attached to a word or phrase, in addition to its strict dictionary definition..""",
"""DIALECT""":"""A more micro level variety of a language (specifically, often a spoken variety) that is characteristic of a particular area, community or group, often with relatively minor differences in vocabulary, style, spelling and pronunciation.""",
"""DICTION""":"""a speaker or writer\'s choice of words..""",
"""DIDACTIC""":"""form of fiction or nonfiction that teaches a specific lesson or moral or provides a model of correct behavior or thinking..""",
"""COLLOQUIALISM""":"""a word or phrase in everyday use in conversation and informal writing but is inappropriate for formal situations. EXAMPLE: \"He\'s out of his head if he thinks I\'m gonna go for such a stupid idea..""",
"""COMEDY""":"""in general, a story that ends with a happy resolution of the conflicts faced by the main character or characters..""",
"""EPIGRAPH""":"""a quotation or aphorism at the beginning of a literary work suggestive of the theme..""",
"""EPITHET""":"""an adjective or adjective phrase applied to a person or thing that is frequently used to emphasize a characteristic quality. \"Father of our country\" and \"the great Emancipator\" are examples. A Homeric epithet is a compound adjective used with a person or thing: \"swift-footed Achilles\", \"rosy-fingered dawn.\".""",
"""ESSAY""":"""a short piece of nonfiction prose in which the writer discusses some aspect of a subject..""",
"""ARGUMENTATION""":"""one of the four forms of discourse which uses logic, ethics, and emotional appeals (logos, ethos, pathos) to develop an effective means to convince the reader to think or act in a certain way..""",
"""PERSUASION""":"""relies more on emotional appeals than on facts.""",
"""ARGUMENT""":"""form of persuasion that appeals to reason instead of emotion to convince an audience to think or act in a certain way..""",
"""CAUSAL RELATIONSHIP""":"""Form of argumentation in which the writer claims that one thing results from another, often used as part of a logical argument..""",
"""DESCRIPTION""":"""a form of discourse that uses language to create a mood or emotion..""",
"""EXPOSITION""":"""one of the four major forms of discourse, in which something is explained or \"set forth.\".""",
"""NARRATIVE""":"""the form of discourse that tells about a series of events..""",
"""EXPLICATION""":"""act of interpreting or discovering the meaning of a text, usually involves close reading and special attention to figurative language..""",
"""EULOGY""":"""A great praise or commendation, a laudatory speech, often about someone who has died.""",
"""EUPHONY""":"""Agreeableness of sound, pleasing effect to the ear, especially a pleasant sounding or harmonious combination or succession of words""",
"""FABLE""":"""A very short story told in prose or poetry that uses anthropomorphism and, or, personification to teach a practical lesson about how to succeed in life.""",
"""FARCE""":"""a type of comedy in which ridiculous and often stereotyped characters are involved in silly, far-fetched situations.""",
"""FIGURATIVE LANGUAGE""":"""Words which are inaccurate if interpreted literally, but are used to describe. Similes and metaphors are common forms""",
"""FLASHBACK""":"""a scene that interrupts the normal chronological sequence of events in a story to depict something that happened at an earlier time.""",
"""FOIL""":"""A character who acts as contrast to another character. Often a funny side kick to the dashing hero, or a villain contrasting the hero""",
"""FORESHADOWING""":"""the use of hints and clues to suggest what will happen later in a plot.""",
"""HUBRIS""":"""A negative term that implies both arrogant, excessive self-pride or self-confidence, and a lack of some important perception or insight due to pride in one\'s abilities. This overwhelming pride inevitably leads to a downfall.""",
"""HYPERBOLE""":"""a figure of speech that uses an incredible exaggeration or overstatement, for effect. \"If I told you once, I\'ve told you a million times....\"""",
"""IMAGERY""":"""the use of language to evoke a picture or a concrete sensation of a person , a thing, a place, or an experience.""",
"""IRONY""":"""a discrepancy between appearances and reality.""",
"""VERBAL IRONY""":"""occurs when someone says one thing but really means something else.""",
"""SITUATIONAL IRONY""":"""takes place when there is a discrepancy between what is expected to happen, or what would be appropriate to happen, and what really does happen.""",
"""DRAMATIC IRONY""":"""is so called because it is often used on stage. A character in the play or story thinks one thing is true, but the audience or reader knows better.""",
"""LITOTES""":"""is a form of understatement in which the positive form is emphasized through the negation of a negative form: Hawthorne--- \"...the wearers of petticoat and farthingale...stepping forth into the public ways, and wedging their not unsubstantial persons, if occasion were, into the throng...\"""",
"""LOCAL COLOR""":"""a term applied to fiction or poetry which tends to place special emphasis on a particular setting, including its customs, clothing, dialect and landscape.""",
"""METAPHOR""":"""a figure of speech that makes a comparison between two unlike things without the use of such specific words of comparison as like, as, than, or resembles.""",
"""IMPLIED METAPHOR""":"""does not state explicitly the two terms of the comparison: \"I like to see it lap the miles\" is an implied metaphor in which the verb lap implies a comparison between \"it\" and some animal that \"laps\" up water.""",
"""EXTENDED METAPHOR""":"""is a metaphor that is extended or developed as far as the writer wants to take it. (conceit if it is quite elaborate).""",
"""DEAD METAPHOR""":"""is a metaphor that has been used so often that the comparison is no longer vivid: \"The head of the house\", \"the seat of the government\", \"a knotty problem\" are all dead metaphors. Could also be classified as a cliché.""",
"""MIXED METAPHOR""":"""is a metaphor that has gotten out of control and mixes its terms so that they are visually or imaginatively incompatible. \"The President is a lame duck who is running out of gas.\"""",
"""METONYMY""":"""a figure of speech in which a person, place, or thing, is referred to by something closely associated with it. \"We requested from the crown support for our petition.\" The crown is used to represent the monarch.""",
"""MOOD""":"""An internal feeling that is created either in the reader or in the characters by a writer's diction and the details selected. (related to atmosphere.)""",
"""MOTIF""":"""a recurring image, word, phrase, action, idea, object, or situation used throughout a work (or in several works by one author), unifying the work by tying the current situation to previous ones, or new ideas to the theme. EXAMPLE Kurt Vonnegut uses \"So it goes\" throughout Slaughterhouse-Five to remind the reader of the senselessness of death.""",
"""MOTIVATION""":"""the reasons for a character\'s behavior.""",
"""ONOMATOPOEIA""":"""the use of words whose sounds echo their sense. \"Pop.\" \"Zap.\"""",
"""OXYMORON""":"""a figure of speech that combines opposite or contradictory terms in a brief phrase. \"Jumbo shrimp.\" \"Pretty ugly.\" \"Bitter-sweet\"""",
"""PARABLE""":"""A relatively short story that teaches a moral, or lesson without the use of anthropomorphism and, or, personification about how to lead a good life.""",
"""PARADOX""":"""a statement that appears self-contradictory, but that reveals a kind of truth.""",
"""PARODY""":"""a work that makes fun of another work by imitating some aspect of the writer\'s style.""",
"""PERSONIFICATION""":"""a figure of speech in which human specific characteristics are attributed to inanimate objects.""",
"""PLOT""":"""the series of related events in a story or play, sometimes called the storyline.""",
"""EXPOSITION""":"""introduces characters, situation, and setting""",
"""RISING ACTION""":"""complications in conflict and situations (may introduce new ones as well)""",
"""CLIMAX""":"""that point in a plot that creates the greatest intensity, suspense, or interest. Also called \"turning point\"""",
"""FALLING ACTION""":"""the point in the plot where the conflicts begin to resolve""",
"""RESOLUTION""":"""the conclusion of a story, when all or most of the conflicts have been settled, often called the denouement.""",
"""POINT OF VIEW""":"""the vantage point from which the writer tells the story.""",
"""FIRST PERSON POINT OF VIEW""":"""one of the characters tells the story. (typically uses first person pronouns: I, me, my, us, we,...)""",
"""SECOND PERSON POINT OF VIEW""":"""the narrator instructs the reader as if they are telling the reader what they are to experience. (typically uses 2nd person pronoun: you)""",
"""THIRD PERSON POINT OF VIEW""":"""an unknown narrator, tells the story, but this narrator zooms in to focus on the thoughts and feelings of only one character. (typically uses 3rd person pronouns: he, she, it, they, them...)""",
"""OMNISCIENT POINT OF VIEW""":"""an omniscient or all-knowing narrator tells the story, also using the third person pronouns. This narrator, instead of focusing on one character only, often tells us everything about many characters.""",
"""OBJECTIVE POINT OF VIEW""":"""a narrator who is totally impersonal and objective tells the story, with no comment on any characters or events.""",
"""PROTAGONIST""":"""the central character in a story, the one who initiates or drives the action. Usually the hero or anti-hero, in a tragic hero, like John Proctor of The Crucible, there is always a hamartia, or tragic flaw in his character which will lead to his downfall.""",
"""PUN""":"""a \"play on words\" based on the multiple meanings of a single word or on words that sound alike but mean different things.""",
"""RHETORIC""":"""Art of effective communication, especially persuasive discourse.""",
"""RHETORICAL QUESTION""":"""a question asked for an effect, and not actually requiring an answer.""",
"""ROMANCE""":"""in general, a story in which an idealized hero or heroine undertakes a quest and is successful.""",
"""SATIRE""":"""a type of writing that ridicules the shortcomings of people or institutions in an attempt to bring about a change.""",
"""SIBILANCE""":"""characterized by a hissing sound noting sounds like those spelled with s in this""",
"""SIMILE""":"""a figure of speech that makes an explicit comparison between two unlike things, using words such as like, as , than, or resembles.""",
"""STEREOTYPE""":"""a fixed idea or conception of a character or an idea which does not allow for any individuality, often based on religious, social, or racial prejudices.""",
"""STREAM OF CONSCIOUSNESS""":"""a style of writing that portrays the inner (often chaotic) workings of a character\'s mind.""",
"""STYLE""":"""the distinctive way in which a writer uses language: a writer\'s distinctive use of diction, tone, and syntax.""",
"""SUSPENSE""":"""a feeling of uncertainty and curiosity about what will happen next in a story.""",
"""SYMBOL""":"""a person, place, thing, or event that has meaning in itself and that also stands for something more than itself""",
"""SYNECDOCHE""":"""a figure of speech in which a part represents the whole. \"If you don\'t drive properly, you will lose your wheels.\" The wheels represent the entire car.""",
"""TALL TALE""":"""an outrageously exaggerated, humorous story that is obviously unbelievable.""",
"""THEME""":"""the insight about human life that is revealed in a literary work.""",
"""TONE""":"""the attitude a writer takes toward the subject of a work, the characters in it, or the audience, revealed through diction, figurative language, and organization.""",
"""TRAGEDY""":"""in general, a story in which a heroic character either dies or comes to some other unhappy end.""",
"""TRAGIC FLAW""":"""A fatal weakness or ignorance in a character that brings them to their end.""",
"""UNDERSTATEMENT""":"""a statement that says less than what is meant.Example: During the second war with Iraq, American troops complained of a fierce sand storm that made even the night-vision equipment useless. A British commando commented about the storm: \"It\'s a bit breezy.\"""",
"""UNRELIABLE NARRATOR""":"""A narrator who, intentionally or unintentionally, relates events of a story is a subjective and distorted manner. The author usually provides an indication early in the story that the narrator is not to be completely trusted.""",
"""VERNACULAR""":"""The macro level language spoken by the people who live in a particular locality. The vernacular of the United States is English.""",
"CONSONANCE" : "the repetition of similar consonant sounds anywhere within words that are placed close together.",
"""ALLITERATION""":"""repetition of the same or similar consonant sounds in words that are close together.""",
"ZOOMORPHISM" : "a figure of speech in which animal specific characteristics are attributed to humans." ,
"""ANAPHORA""":"""Repetition of a word, phrase, or clause at the beginning of two or more sentences in a row. This is a deliberate form of repetition and helps make the writer\'s point more coherent""",
"""ANASTROPHE""":"""Inversion of the usual, normal, or logical order of the parts of a sentence. Purpose is rhythm or emphasis or euphony. It is a fancy word for inversion.""",
"""ANTIMETABOLE""":"""Repetition of words in successive clauses in reverse grammatical order.""",
"""ANTITHESIS""":"""Balancing words, phrases, or ideas that are strongly contrasted, often by means of grammatical structure.""",
"""APPOSITION""":"""Placing in immediately succeeding order of two or more coordinate elements, the latter of which is an explanation, qualification, or modification of the first (often set off by a colon). Paine: \"These are the times that try men\'s souls: The summer soldier and the sunshine patriot will in this crisis, shrink from the service of his country, but he that stands it Now, deserves the love and thanks of man and woman.\"""",
"""BALANCE""":"""Constructing a sentence so that both halves are about the same length and importance. Sentences can be unbalanced to serve a special effect as well.""",
"""EPANALEPSIS""":"""device of repetition in which the same expression (single word or phrase) is repeated both at the beginning and at the end of the line, clause, or sentence. EXAMPLE Voltaire: \"Common sense is not so common.\"""",
"""EPISTROPHE""":"""Device of repetition in which the same expression (single word or phrase) is repeated at the end of two or more lines, clauses, or sentences (it is the opposite of anaphora).""",
"""HYPOTACTIC SENTENCE""":"""sentence marked by the use of connecting words between clauses or sentences, explicitly showing the logical or other relationships between them. (Use of such syntactic subordination of just one clause to another is known as hypotaxis). I am tired because it is hot.""",
"""INVERSION""":"""the reversal of the normal word order in a sentence or phrase.""",
"""JUXTAPOSITION""":"""poetic and rhetorical device in which normally unassociated ideas, words, or phrases are placed next to one another, creating an effect of surprise and wit.""",
"""LOOSE SENTENCE""":"""one in which the main clause comes first, followed by further dependent grammatical units. See periodic sentence.""",
"""PARALLEL STRUCTURE""":"""the repetition of words or phrases that have similar grammatical structures (parallelism).""",
"""PARATACTIC SENTENCE""":"""simply juxtaposes clauses or sentences. I am tired: it is hot.""",
"""PERIODIC SENTENCE""":"""sentence that places the main idea or central complete thought at the end of the sentence, after all introductory elements.""",
"""POLYSYNDETON""":"""sentence which uses a conjunction with NO commas to separate the items in a series. Instead of X, Y, and Z... Polysyndeton results in X and Y and Z...""",
"""SYNTACTIC FLUENCY""":"""Ability to create a variety of sentence structures, appropriately complex and/or simple and varied in length.""",
"""SYNTACTIC PERMUTATION""":"""Sentence structures that are extraordinarily complex and involved. Often difficult for a reader to follow.""",
"""SYNTAX""":"""The manner in which words are arranged to form sentences""",
"""TELEGRAPHIC SENTENCE""":"""A sentence shorter than five words in length.""",
"""TRICOLON""":"""Sentence of three parts of equal importance and length, usually three independent clauses.""",
"""UNITY""":"""Unified parts of the writing are related to one central idea or organizing principle. Unity is dependent upon coherence""",
"""ACT""":"""The major structural division in a drama. They are divided into scenes. They may contain shifts in time and place.""",
"""ASIDE""":"""In drama, a few words or short passage spoke in an undertone or to the audience. By convention, other characters onstage are deaf to it.""",
"""CATHARSIS""":"""The purging of the feelings of pity and fear. According to Aristotle the audience should experiences catharsis at the end of a tragedy.""",
"""CHORUS""":"""In a classical drama, this is a group of characters placed on stage to comment upon the action and express traditional wisdom. It is employed most often in traditional Greek drama.""",
"""FOURTH WALL""":"""The imaginary wall that separates the spectator/audience from the action taking place on stage. In a traditional theatre setting (as opposed to a theatre in the round) this imaginary wall has been removed so that the spectator can \"peep\" into the fictional world and see what is going on. If the audience is addressed directly, this is referred to as \"breaking the ________.\"""",
"""MONOLOGUE""":"""A speech by a single character without another character\'s response. The character however, is speaking to someone else or even a group of people.""",
"""SCENE""":"""A traditional segment in a play. They are used to indicate (1) a change in time (2) a change in location, (3) provides a jump from one subplot to another, (4) introduces new characters (5) rearrange the actors on the stage. Traditionally plays are composed of acts, broken down into these.""",
"""SOLILOQUY""":"""a long speech made by a character in a play while no other characters are on stage.""",
"""STAGE DIRECTION""":"""A playwright\'s descriptive or interpretive comments that provide readers (as well as actors and directors) with information about the dialogue, setting, and action of a play. Modern playwrights tend to include substantial amounts of these, while earlier playwrights typically use them more sparsely, implicitly, or not at all.""",
"""THEATER OF THE ABSURD""":"""A postwar European genre of drama that depicts the grotesque common plight of human beings thrown by accident into an irrational and meaningless world. Ex. Waiting for Godot""",
"""CAESURA""":"""A pause within a line of poetry. They usually appear in the middle of a line with the use of a comma or period.""",
"""CHIASMUS""":"""In poetry, a type of rhetorical balance in which the second part is syntactically balanced against the first, but with the parts reversed. EXAMPLE Coleridge: \"Flowers are lovely, love is flowerlike.\" In prose this is called antimetabole.""",
"""CONCEIT""":"""an elaborate metaphor that compares two things that are startlingly different. Often an extended metaphor.""",
"""CONFESSIONAL POETRY""":"""a twentieth century term used to describe poetry that uses intimate material from the poet\'s life.""",
"""CLOSED COUPLET""":"""Two rhymed lines that contain and independent and complete thought or statement. EX. \"I should have been a pair of ragged claws/ Scuttling across the floors of silent seas.\" (Eliot)""",
"""COUPLET""":"""two consecutive rhyming lines of poetry. EX. \"This day, whate\'er the fates decree./ Shall still be kept with joy by me...\" (Swift)""",
"""DRAMATIC MONOLOGUE""":"""A poem written as a speech made by a character. Typically the persona will reveal private desires, weaknesses, crimes, or maybe in wrongdoings.""",
"""ELEGY""":"""a poem of mourning, usually about someone who has died.""",
"""END STOPPED LINE""":"""A line of poetry or verse that ends in a full pause usually indicated by a mark of punctuation.""",
"""ENJAMBMENT""":"""A line of poetry that does not end will a full pause (punctuation) which should then be read in conjunction with the next line of poetry without pausing.""",
"""EPIC""":"""a long narrative poem, written in heightened language , which recounts the deeds of a heroic character who embodies the values of a particular society.""",
"""FREE VERSE""":"""poetry that does not conform to a regular meter or rhyme scheme.""",
"""LYRIC POEM""":"""a poem that does not tell a story but expresses the personal feelings or thoughts of the speaker. A ballad tells a story.""",
"""METER""":"""The count of rhythmic patterns of stressed and unstressed syllables in poetry. A poem that does not contain this is said to be blank verse. This is combined with metrical feet.""",
"""Dimeter""":"""A meter consisting of two metrical feet per line""",
"""Heptameter""":"""A meter consisting of seven metrical feet per line""",
"""Hexameter""":"""A meter consisting of six metrical feet per line""",
"""Monometer""":"""A meter consisting of one metrical foot per line""",
"""Octameter""":"""A meter consisting of eight metrical feet per line""",
"""Pentameter""":"""A meter consisting of five metrical feet per line""",
"""Tetrameter""":"""A meter consisting of four metrical feet per line""",
"""Trimeter""":"""A meter consisting of three metrical feet per line""",
"""METRICAL FOOT""":"""The basic unit of measurement of metrical poetry that counts the stressed and unstressed syllables in a poem. This is combined with meter.""",
"""Anapest""":"""a metrical foot that contains two unstressed syllables followed by a stressed syllable- \"on a boat\"\'""",
"""Dactyl""":"""a metrical foot that contains one stressed syllable followed by two unstressed syllables- \"Bat-ter-y""",
"""Iamb""":"""a metrical foot that contains one unstressed syllable followed by one stressed syllable- \"ex-it and be-long\"""",
"""Spondee""":"""a metrical foot that contains two stressed syllables and is used generally for emphasis- \"good men\"""",
"""Trochee""":"""a metrical foot that contains one stressed syllable followed by an unstressed syllable- \"sum-mer and chor-us\"""",
"""QUATRAIN""":"""four lines of a poem that can be considered as a stanza or a poem consisting of four lines.""",
"""REFRAIN""":"""a word, phrase, line, or group of lines that is repeated, for effect, several times in a poem.""",
"""RHYTHM""":"""a rise and fall of the voice produced by the alternation of stressed and unstressed syllables in language. If this is fixed in a poem it is considered a meter.""",
"""RHYME""":"""Two or more words that contain an identical or similar sounds that are repeated.""",
"""End Rhyme""":"""Rhyme that occurs at the ends of lines of poetry rather than within.""",
"""Exact Rhyme""":"""Rhyme that consists of words that are identical in sound- go/slow""",
"""Feminine Rhyme""":"""A rhyme of two or more syllables with a stress on a syllable other than the last- tur-tle and fer-tle""",
"""Internal Rhyme""":"""Rhyme that occurs within lines of poetry rather than at the end""",
"""Masculine Rhyme""":"""Rhyme that consists of stressed syllables- either one syllable words \"fox and socks\" or words whose final syllable is stressed \"con-trive and sur-vive\"""",
"""Slant Rhyme""":"""A rhyme in which the final consonant sounds are the same but the vowels are slightly different- \"letter and litter or bone and bean\"""",
"Scansion" : "The method used to determine the rhythm or meter in a poem. This is done by counting meter and metrical feet.",
"Sestet" : "Six lines of a poem that can be considered as a stanza or a poem consisting of six lines.",
"Tercet" : "Three lines of a poem that are formed into one stanza that usually rhymes.",
}

#Genres

AllWords = ['ALLEGORY', 'ALLUSION', 'AMBIGUITY', 'ANALOGY', 'ANECDOTE', 'ANTAGONIST', 'ANTIHERO', 'ANTHROPOMORPHISM', 'APHORISM', 'APOSTROPHE', 'ARCHETYPE', 'ASSONANCE', 'ASYNDETON', 'ATMOSPHERE', 'BILDUNGSROMAN', 'CACOPHONY', 'CHARACTERIZATION', 'INDIRECT CHARACTERIZATION', 'DIRECT CHARACTERIZATION', 'STATIC CHARACTER', 'DYNAMIC CHARACTER', 'FLAT CHARACTER', 'ROUND CHARACTER', 'CLICHÉ', 'CONFLICT', 'EXTERNAL CONFLICT', 'INTERNAL CONFLICT', 'CONNOTATION', 'DIALECT', 'DICTION', 'DIDACTIC', 
'COLLOQUIALISM', 'COMEDY', 'EPIGRAPH', 'EPITHET', 'ESSAY', 'ARGUMENTATION', 'PERSUASION', 'ARGUMENT', 'CAUSAL RELATIONSHIP', 'DESCRIPTION', 'EXPOSITION', 'NARRATIVE', 'EXPLICATION', 'EULOGY', 'EUPHONY', 'FABLE', 'FARCE', 'FIGURATIVE LANGUAGE', 'FLASHBACK', 'FOIL', 'FORESHADOWING', 'HUBRIS', 'HYPERBOLE', 'IMAGERY', 'IRONY', 'VERBAL IRONY', 'SITUATIONAL IRONY', 'DRAMATIC IRONY', 'LITOTES', 'LOCAL COLOR', 'METAPHOR', 'IMPLIED METAPHOR', 'EXTENDED METAPHOR', 'DEAD METAPHOR', 'MIXED METAPHOR', 'METONYMY', 'MOOD', 'MOTIF', 'MOTIVATION', 'ONOMATOPOEIA', 'OXYMORON', 'PARABLE', 'PARADOX', 'PARODY', 'PERSONIFICATION', 'PLOT', 'RISING ACTION', 'CLIMAX', 'FALLING ACTION', 'RESOLUTION', 'POINT OF VIEW', 'FIRST PERSON POINT OF VIEW', 'SECOND PERSON POINT OF VIEW', 'THIRD PERSON POINT OF VIEW', 'OMNISCIENT POINT OF VIEW', 'OBJECTIVE POINT OF VIEW', 'PROTAGONIST', 'PUN', 'RHETORIC', 'RHETORICAL QUESTION', 'ROMANCE', 'SATIRE', 'SIBILANCE', 'SIMILE', 'STEREOTYPE', 'STREAM OF CONSCIOUSNESS', 'STYLE', 'SUSPENSE', 'SYMBOL', 'SYNECDOCHE', 'TALL TALE', 'THEME', 'TONE', 'TRAGEDY', 'TRAGIC FLAW', 'UNDERSTATEMENT', 'UNRELIABLE NARRATOR', 'VERNACULAR', 'CONSONANCE', 'ALLITERATION', 'ZOOMORPHISM', 'ANAPHORA', 'ANASTROPHE', 'ANTIMETABOLE', 'ANTITHESIS', 'APPOSITION', 'BALANCE', 'EPANALEPSIS', 'EPISTROPHE', 'HYPOTACTIC SENTENCE', 'INVERSION', 'JUXTAPOSITION', 'LOOSE SENTENCE', 'PARALLEL STRUCTURE', 'PARATACTIC SENTENCE', 'PERIODIC SENTENCE', 'POLYSYNDETON', 'SYNTACTIC FLUENCY', 'SYNTACTIC PERMUTATION', 'SYNTAX', 'TELEGRAPHIC SENTENCE', 'TRICOLON', 'UNITY', 'ACT', 'ASIDE', 'CATHARSIS', 'CHORUS', 'FOURTH WALL', 'MONOLOGUE', 'SCENE', 'SOLILOQUY', 'STAGE DIRECTION', 'THEATER OF THE ABSURD', 'CAESURA', 'CHIASMUS', 'CONCEIT', 'CONFESSIONAL POETRY', 'CLOSED COUPLET', 'COUPLET', 'DRAMATIC MONOLOGUE', 'ELEGY', 'END STOPPED LINE', 'ENJAMBMENT', 'EPIC', 'FREE VERSE', 'LYRIC POEM', 'METER', 'Dimeter', 'Heptameter', 'Hexameter', 'Monometer', 'Octameter', 'Pentameter', 'Tetrameter', 'Trimeter', 'METRICAL FOOT', 'Anapest', 'Dactyl', 'Iamb', 'Spondee', 'Trochee', 'QUATRAIN', 'REFRAIN', 'RHYTHM', 'RHYME', 'End Rhyme', 'Exact Rhyme', 'Feminine Rhyme', 'Internal Rhyme', 'Masculine Rhyme', 'Slant Rhyme', 'Scansion', 'Sestet', 'Tercet']
GrammarWords = ['ALLEGORY', 'ALLUSION', 'AMBIGUITY', 'ANALOGY', 'ANECDOTE', 'ANTAGONIST', 'ANTIHERO', 'ANTHROPOMORPHISM', 'APHORISM', 'APOSTROPHE', 'ARCHETYPE', 'ASSONANCE', 'ASYNDETON', 'ATMOSPHERE', 'BILDUNGSROMAN', 'CACOPHONY', 'CHARACTERIZATION', 'INDIRECT CHARACTERIZATION', 'DIRECT CHARACTERIZATION', 'STATIC CHARACTER', 'DYNAMIC CHARACTER', 'FLAT CHARACTER', 'ROUND CHARACTER', 'CLICHÉ', 'CONFLICT', 'EXTERNAL CONFLICT', 'INTERNAL CONFLICT', 'CONNOTATION', 'DIALECT', 'DICTION', 'DIDACTIC', 'COLLOQUIALISM', 'COMEDY', 'EPIGRAPH', 'EPITHET', 'ESSAY', 'ARGUMENTATION', 'PERSUASION', 'ARGUMENT', 'CAUSAL RELATIONSHIP', 'DESCRIPTION', 'EXPOSITION', 'NARRATIVE', 'EXPLICATION', 'EULOGY', 'EUPHONY', 'FABLE', 'FARCE', 'FIGURATIVE LANGUAGE', 'FLASHBACK', 'FOIL', 'FORESHADOWING', 'HUBRIS', 'HYPERBOLE', 'IMAGERY', 'IRONY', 'VERBAL IRONY', 'SITUATIONAL IRONY', 'DRAMATIC IRONY', 'LITOTES', 'LOCAL COLOR', 'METAPHOR', 'IMPLIED METAPHOR', 'EXTENDED METAPHOR', 'DEAD METAPHOR', 'MIXED METAPHOR', 'METONYMY', 'MOOD', 'MOTIF', 'MOTIVATION', 'ONOMATOPOEIA', 'OXYMORON', 'PARABLE', 'PARADOX', 'PARODY', 'PERSONIFICATION', 'PLOT', 'RISING ACTION', 'CLIMAX', 'FALLING ACTION', 'RESOLUTION', 'POINT OF VIEW', 'FIRST PERSON POINT OF VIEW', 'SECOND PERSON POINT OF VIEW', 'THIRD PERSON POINT OF VIEW', 'OMNISCIENT POINT OF VIEW', 'OBJECTIVE POINT OF VIEW', 'PROTAGONIST', 'PUN', 'RHETORIC', 'RHETORICAL QUESTION', 'ROMANCE', 'SATIRE', 'SIBILANCE', 'SIMILE', 'STEREOTYPE', 'STREAM OF CONSCIOUSNESS', 'STYLE', 'SUSPENSE', 'SYMBOL', 'SYNECDOCHE', 'TALL TALE', 'THEME', 'TONE', 'TRAGEDY', 'TRAGIC FLAW', 'UNDERSTATEMENT', 'UNRELIABLE NARRATOR', 'VERNACULAR', 'CONSONANCE', 'ALLITERATION', 'ZOOMORPHISM']
SyntaxWords = ['ANAPHORA', 'ANASTROPHE', 'ANTIMETABOLE', 'ANTITHESIS', 'APPOSITION', 'BALANCE', 'EPANALEPSIS', 'EPISTROPHE', 'HYPOTACTIC SENTENCE', 'INVERSION', 'JUXTAPOSITION', 'LOOSE SENTENCE', 'PARALLEL STRUCTURE', 'PARATACTIC SENTENCE', 'PERIODIC SENTENCE', 'POLYSYNDETON', 'SYNTACTIC FLUENCY', 'SYNTACTIC PERMUTATION', 'SYNTAX', 'TELEGRAPHIC SENTENCE', 'TRICOLON', 'UNITY']
DramaWords = ['ACT', 'ASIDE', 'CATHARSIS', 'CHORUS', 'FOURTH WALL', 'MONOLOGUE', 'SCENE', 'SOLILOQUY', 'STAGE DIRECTION', 'THEATER OF THE ABSURD']
PoeticWords = ['CAESURA', 'CHIASMUS', 'CONCEIT', 'CONFESSIONAL POETRY', 'CLOSED COUPLET', 'COUPLET', 'DRAMATIC MONOLOGUE', 'ELEGY', 'END STOPPED LINE', 'ENJAMBMENT', 'EPIC', 'FREE VERSE', 'LYRIC POEM', 'METER', 'Dimeter', 'Heptameter', 'Hexameter', 'Monometer', 'Octameter', 'Pentameter', 'Tetrameter', 'Trimeter', 'METRICAL FOOT', 'Anapest', 'Dactyl', 'Iamb', 'Spondee', 'Trochee', 'QUATRAIN', 'REFRAIN', 'RHYTHM', 'RHYME', 'End Rhyme', 'Exact Rhyme', 'Feminine Rhyme', 'Internal Rhyme', 'Masculine Rhyme', 'Slant Rhyme', 'Scansion', 'Sestet', 'Tercet']

GenredVocabWords = {"poetic" : PoeticWords, "syntax" : SyntaxWords, "grammatical" : GrammarWords, "drama" : DramaWords, "All IB Literary Terms" : AllWords}



gifs = ["https://tenor.com/view/spongebob-spongebob-meme-spunch-bob-spunch-bop-skill-issue-gif-23692514","https://tenor.com/view/skill-issue-club-penguin-club-penguin-dance-skill-issue-gif-24610458",
"https://tenor.com/view/skill-issue-among-us-skill-issue-killer-bean-gif-24855216",
"https://tenor.com/view/skillissue-skill-issue-gif-22125481",
"https://tenor.com/view/skill-issue-xd-gif-23389115",
"https://tenor.com/view/blox-cards-skill-issue-gif-22773141"
"https://tenor.com/view/miku-hatsune-miku-miku-hatsune-skill-skill-issue-gif-24669779", "https://tenor.com/view/cat-cats-awkward-awkward-cat-cat-awkward-gif-24906225"
,"https://tenor.com/view/blox-cards-skill-issue-gif-22773141",
"https://tenor.com/view/skill-issue-gif-19411985",
"https://tenor.com/view/skill-issue-skill-issue-comically-large-spoon-spoon-gif-22697060",
"https://tenor.com/view/didnt-ask-didnt-ask-dont-care-dont-gif-23967669",
"https://tenor.com/view/skill-issue-klein-bottle-glass-fluid-pinky-promise-gif-25312176",
"https://tenor.com/view/skill-issue-difference-in-skill-pibby-adult-swim-flintstones-gif-23624283",]

genreColors = {"poetic" : 0x9ccfe7, "syntax" : 0x977fd7 , "grammatical" : 0xf5a9cb, "drama" : 0xffffc2, "All IB Literary Terms" : 0xA020F0}

